### ISSUE TITLE
Undocumented version of xodus used

### ISSUE THREAD

**Issue by jansorg** [JetBrains/xodus-dnq#36]
I'm interested to use the dnq library with xodus (I'm new to both). 
I found out that I have to add `maven { url 'http://repository.jetbrains.com/xodus' }` to make the dependencies resolve.

https://repo.maven.apache.org/maven2/org/jetbrains/xodus/dnq-open-api/1.1.226/dnq-open-api-1.1.226.pom uses Xodus `1.0.2766`, the latest public release is `1.1.0` (https://github.com/JetBrains/xodus).

Which version of Xodus should I use? 
Is there a version of xodus-dnq which uses the 1.1.0 release?

Thanks a lot!

**Comment by sedovalx** [comment]
There is no version of the `xodus-dnq` that uses `xodus` 1.1.0 yet. You can safely use the `1.0.2766` version of `xodus` until a new version of `xodus-dnq` is released. Hopefully, it won't take long time.

**Comment by mazine** [comment]
I'll update the version of `xodus-dnq` to 1.1.0 and make a release.

**Comment by mazine** [comment]
I've updated the version of `Xodus` to 1.1.0 and published it to Maven Central. Now should wait until Maven Central index it. May take up to several hours.

**Comment by jansorg** [comment]
@mazine @sedovalx Thank you!
