### ISSUE TITLE
Missing way to locate by EntityId

### ISSUE THREAD

**Issue by jansorg** [JetBrains/xodus-dnq#38]
I couldn't find a way to load an XdEntity by EntityId (a string with a value of an EntityId).

I guess that there's a better way, but here's my code to to this:
```kotlin
import kotlinx.dnq.XdEntity
import kotlinx.dnq.XdNaturalEntityType

open class XdCustomEntityType<T : XdEntity>() : XdNaturalEntityType<T>(storeContainer = ThreadLocalStoreContainer) {
    fun find(id: String): T? {
        val transaction = (XdOrganisation.entityStore.threadSession
                ?: throw IllegalStateException("New entities can be created only in transactional block"))

        val entity = transaction.getEntity(transaction.toEntityId(id))
        return wrap(entity).apply {
            constructor()
        }
    }
}
```

**Comment by sedovalx** [comment]
`EntityId` is a low level class. Why do you need to search by it? Usually, you have an identity field in a base class of your xd-hierarchy:
```
abstract class XdIdEntityType<XD : XdIdEntity> : XdNaturalEntityType<XD>(ThreadLocalStoreContainer) {
    fun findById(id: Long): XD? {
        return all().firstOrNull(XdIdEntity::id eq id)
    }
}

abstract class XdIdEntity(entity: Entity) : XdEntity(entity) {
    companion object : XdIdEntityType<XdIdEntity>()
    
    val id by xdRequiredLongProp(unique = true) { min(0) }
}
```
And there is a kind of agreement that all operations over xd-entities that involve data reads or writes should be done in a `transactional` block. So, typically, there is no need to check the current transaction in xd-methods. 
Anyway, you are on a right way if you think you need to search by an `EntityId`. Here is how I would do it:
```
val store: TransientEntityStore = TODO()
val entityId: String = TODO()
        
store.transactional { txn ->
    txn.getEntity(txn.toEntityId(entityId)).toXd<XdMyEntity>()
}

```

**Comment by jansorg** [comment]
Thanks @sedovalx , 
I couldn't find a way to have an automatically generated UUID in my entities, so I used the internal id (as suggest at https://github.com/JetBrains/xodus/wiki/Entity-Stores#entities at the end).

I'm now using a halfway automatic solution using UUIDs and a find operation like you suggested.

**Comment by sedovalx** [comment]
You can use `UUID.randomUUID().toString()` in a constructor of your xd-entities:

```
abstract class XdIdEntityType<XD : XdIdEntity> : XdNaturalEntityType<XD>(ThreadLocalStoreContainer) {
    fun findById(id: String): XD? {
        return all().firstOrNull(XdIdEntity::id eq id)
    }
}

abstract class XdIdEntity(entity: Entity) : XdEntity(entity) {
    companion object : XdIdEntityType<XdIdEntity>() 

    val id by xdRequiredStringProp(unique = true, trimmed = true)
}

class XdMyEntuty(entity: Entity) : XdIdEntity(entity) {
   companion object : XdIdEntityType<XdMyEntity>() {
        fun new(name: String) = new {
            this.id = UUID.randomUUID().toString()
            this.name = name
        }
    }

    val name: String by xdStringProp()
}
```

And then `val xd = XdMyEntity.new("Apple")`.

**Comment by lehvolk** [comment]
@sedovalx EntityId is a reliable database identity which can be used as unique entity identity across single database. At the moment we have only one implementation of `EntityId` for which `toString` will return string identity like `typeId-entityLocalId`. Backward API is not supported in xodus-dnq at the moment thus you should make a low-level call `tx.getEntity(tx.toEntityId(entityStringId)).toXd()`.

I think we should definitely support converting EntityId to String and back and type safe search by id across database.
