### ISSUE TITLE
Installation of local dev version?

### ISSUE THREAD

**Issue by jansorg** [JetBrains/xodus-dnq#40]
I wanted to use the current version of Kotlin with Xodus (https://github.com/JetBrains/xodus/pull/17). I can't see a way to install a local snapshot of xodus-dnq. Is there a way to do this?

`./gradlew clean install` reports that task `install` is unavailable.

**Comment by jk1** [comment]
`./gradlew -PpublishTo=http://maven.local publishToMavenLocal`

**Comment by jansorg** [comment]
Thanks
