### ISSUE TITLE
XdEntity.filter and XdEntity.query accepts accepts same construction and behaves different.

### ISSUE THREAD

**Issue by leostryuk** [JetBrains/xodus-dnq#46]
For example 
let us have type `XdFoo` with property `bar` : Long

Expression XdFoo.filter(XdFoo::bar lt 20) should not be compiled or at least throw an exception in runtime.

**Comment by lehvolk** [comment]
Fixed in this [commit](fc362ca33cbfe431511e5b73d9a931e07c6d92b6)
