### ISSUE TITLE
Cache entityConstructor of XdHierarchyNode

### ISSUE THREAD

**Issue by sedovalx** [JetBrains/xodus-dnq#47]
When `XdModel#toXd` is run it uses reflection to get the `entityConstructor`. The result may be cached.

**Comment by lehvolk** [comment]
@sedovalx in terms of JVM `val entityConstructor = entityType.entityConstructor` is class field which initialised during class construction. I see no reason to wrap it into lazy delegate.

**Comment by sedovalx** [comment]
You are absolutely right.
