### ISSUE TITLE
GraalVM/Spring Native Compatibility

### ISSUE THREAD

**Issue by battila7** [JetBrains/xodus-dnq#73]
Hey,

I attempted to embed Xodus and, of course, Xodus DNQ into a Spring project, and turn it into a native executable via GraalVM/Spring Native. Using the latest version of DNQ in Maven Central (`1.4.480`), I was unable to do so, because of how `initMetaData` is implemented.

However, by using the GitHub HEAD, which contains this crucial change: https://github.com/JetBrains/xodus-dnq/commit/915882db248f7bbdf42e17adcb50ee6ee3170502#diff-4ad8a6eb500db387708f3c0bf45d4005c4bd9f8e81463ef793424a8a678667fdL46 (and the removal of `javassist`, of course), I could get Xodus DNQ up & running with Spring Native.

Currently, my project depends on hand-built DNQ JARs, but it'd be much better to obtain them from Maven Central. Therefore, I wanted to ask, whether you plan on releasing a new version in the future, and if so, then when exactly?

Best regards,
Attila

**Comment by lehvolk** [comment]
Hey. This change most probably will be included in 1.5 with other changes which affect DNQ API. At the moment we do not have any ETA on 1.5.

**Comment by battila7** [comment]
Cool, thanks for the update! Will keep on eye on it, and use the hand-built JARs for the time being.
